### ISSUE TITLE
is this used for ali?

### ISSUE THREAD

**Issue by sachin0606** [qttest1/PDK_GoBian#1]
i want firmware for ali3202c. can i use this?

**Comment by qttest1** [comment]
No

**Comment by sachin0606** [comment]
Can you help me in developing firmware for ali3202c?

**Comment by qttest1** [comment]
who are you? personal ? or which customer?

**Comment by sachin0606** [comment]
Can you share me u r mail id will contact you

**Comment by qttest1** [comment]
Sorry, this is only a test account. It can't provide any support.

**Comment by sachin0606** [comment]
I am not asking about this account. I wanted help in developing a stb firmware . As you are in same domain execting.

**Comment by qttest1** [comment]
I'm sorry.  I don't have firmware for ali3202c.

**Comment by sachin0606** [comment]
ok. thanks for your reply.

**Comment by qttest1** [comment]
You're welcome.
